// Code generated by goyacc - DO NOT EDIT.

package jsonpath

import __yyfmt__ "fmt"

type yySymType struct {
	yys           int
	Expr          Expr
	Exprs         []Expr
	FilterExpr    FilterExpr
	MatcherExpr   MatcherExpr
	op            int
	intVal        int
	bytes         uint64
	str           string
	falVal        float64
	boolVal       bool
	duration      string
	val           string
	exprType      int
	strs          []string
	ValExpr       any
	EmptyGroup    any
	BinaryExpr    *BinaryExpr
	CallExpr      *CallExpr
	MemberExpr    MemberExpr
	StringExpr    StringExpr
	IndexExpr     IndexExpr
	RootSymbol    Symbol
	CurrentSymbol Symbol
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault         = 57388
	yyEofCode         = 57344
	ADD               = 57360
	AND               = 57366
	AND2              = 57369
	AT                = 57380
	CLOSE_BRACE       = 57373
	CLOSE_BRACKET     = 57377
	CLOSE_PARENTHESIS = 57375
	COLON             = 57383
	COMMA             = 57382
	DIV               = 57363
	DOLLAR            = 57379
	DOT               = 57378
	DOTDOT            = 57381
	EQ                = 57352
	FALSE             = 57351
	FLOAT             = 57348
	GT                = 57354
	GTE               = 57355
	IDENTIFIER        = 57346
	IN                = 57370
	INT               = 57349
	LT                = 57356
	LTE               = 57357
	MOD               = 57364
	MUL               = 57362
	NEQ               = 57353
	NEXT_CALL         = 57386
	NEXT_SELECT       = 57387
	NIN               = 57371
	NRE               = 57359
	OPEN_BRACE        = 57372
	OPEN_BRACKET      = 57376
	OPEN_PARENTHESIS  = 57374
	OR                = 57367
	OR2               = 57368
	POW               = 57365
	QUESTION          = 57385
	RE                = 57358
	SCOLON            = 57384
	STRING            = 57347
	SUB               = 57361
	TRUE              = 57350
	yyErrCode         = 57345

	yyMaxDepth = 200
	yyTabOfs   = -67
)

var (
	yyPrec = map[int]int{
		EQ:                0,
		NEQ:               0,
		GT:                0,
		GTE:               0,
		LT:                0,
		LTE:               0,
		RE:                0,
		NRE:               0,
		ADD:               1,
		SUB:               1,
		MUL:               1,
		DIV:               1,
		MOD:               1,
		POW:               1,
		AND:               2,
		OR:                2,
		OR2:               2,
		AND2:              2,
		IN:                2,
		NIN:               2,
		OPEN_BRACE:        3,
		CLOSE_BRACE:       3,
		OPEN_PARENTHESIS:  3,
		CLOSE_PARENTHESIS: 3,
		OPEN_BRACKET:      3,
		CLOSE_BRACKET:     3,
		DOT:               4,
		DOLLAR:            4,
		AT:                4,
		DOTDOT:            4,
		COMMA:             4,
		COLON:             4,
		SCOLON:            4,
		QUESTION:          4,
		NEXT_CALL:         5,
		NEXT_SELECT:       5,
	}

	yyXLAT = map[int]int{
		57377: 0,  // CLOSE_BRACKET (54x)
		57382: 1,  // COMMA (54x)
		57376: 2,  // OPEN_BRACKET (54x)
		57375: 3,  // CLOSE_PARENTHESIS (48x)
		57344: 4,  // $end (35x)
		57352: 5,  // EQ (34x)
		57354: 6,  // GT (34x)
		57355: 7,  // GTE (34x)
		57370: 8,  // IN (34x)
		57356: 9,  // LT (34x)
		57357: 10, // LTE (34x)
		57353: 11, // NEQ (34x)
		57371: 12, // NIN (34x)
		57359: 13, // NRE (34x)
		57358: 14, // RE (34x)
		57378: 15, // DOT (27x)
		57381: 16, // DOTDOT (27x)
		57394: 17, // index (27x)
		57401: 18, // selector (24x)
		57380: 19, // AT (17x)
		57349: 20, // INT (17x)
		57379: 21, // DOLLAR (16x)
		57361: 22, // SUB (15x)
		57348: 23, // FLOAT (12x)
		57347: 24, // STRING (12x)
		57346: 25, // IDENTIFIER (11x)
		57398: 26, // member (11x)
		57362: 27, // MUL (9x)
		57392: 28, // expr (8x)
		57400: 29, // segment (8x)
		57395: 30, // intExpr (7x)
		57383: 31, // COLON (4x)
		57396: 32, // matcher (3x)
		57385: 33, // QUESTION (3x)
		57403: 34, // valExpr (3x)
		57390: 35, // callExpr (2x)
		57397: 36, // matchers (2x)
		57374: 37, // OPEN_PARENTHESIS (2x)
		57389: 38, // callArgsExpr (1x)
		57391: 39, // compairOp (1x)
		57351: 40, // FALSE (1x)
		57393: 41, // includeOp (1x)
		57399: 42, // range (1x)
		57402: 43, // start (1x)
		57350: 44, // TRUE (1x)
		57388: 45, // $default (0x)
		57360: 46, // ADD (0x)
		57366: 47, // AND (0x)
		57369: 48, // AND2 (0x)
		57373: 49, // CLOSE_BRACE (0x)
		57363: 50, // DIV (0x)
		57345: 51, // error (0x)
		57364: 52, // MOD (0x)
		57386: 53, // NEXT_CALL (0x)
		57387: 54, // NEXT_SELECT (0x)
		57372: 55, // OPEN_BRACE (0x)
		57367: 56, // OR (0x)
		57368: 57, // OR2 (0x)
		57365: 58, // POW (0x)
		57384: 59, // SCOLON (0x)
	}

	yySymNames = []string{
		"CLOSE_BRACKET",
		"COMMA",
		"OPEN_BRACKET",
		"CLOSE_PARENTHESIS",
		"$end",
		"EQ",
		"GT",
		"GTE",
		"IN",
		"LT",
		"LTE",
		"NEQ",
		"NIN",
		"NRE",
		"RE",
		"DOT",
		"DOTDOT",
		"index",
		"selector",
		"AT",
		"INT",
		"DOLLAR",
		"SUB",
		"FLOAT",
		"STRING",
		"IDENTIFIER",
		"member",
		"MUL",
		"expr",
		"segment",
		"intExpr",
		"COLON",
		"matcher",
		"QUESTION",
		"valExpr",
		"callExpr",
		"matchers",
		"OPEN_PARENTHESIS",
		"callArgsExpr",
		"compairOp",
		"FALSE",
		"includeOp",
		"range",
		"start",
		"TRUE",
		"$default",
		"ADD",
		"AND",
		"AND2",
		"CLOSE_BRACE",
		"DIV",
		"error",
		"MOD",
		"NEXT_CALL",
		"NEXT_SELECT",
		"OPEN_BRACE",
		"OR",
		"OR2",
		"POW",
		"SCOLON",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {43, 1},
		2:  {28, 1},
		3:  {28, 2},
		4:  {28, 3},
		5:  {28, 3},
		6:  {28, 1},
		7:  {28, 2},
		8:  {28, 3},
		9:  {28, 3},
		10: {28, 2},
		11: {28, 3},
		12: {28, 4},
		13: {28, 4},
		14: {28, 1},
		15: {28, 1},
		16: {28, 3},
		17: {29, 1},
		18: {29, 1},
		19: {29, 1},
		20: {29, 1},
		21: {29, 2},
		22: {29, 2},
		23: {29, 3},
		24: {29, 3},
		25: {29, 3},
		26: {26, 1},
		27: {26, 1},
		28: {35, 4},
		29: {35, 3},
		30: {38, 1},
		31: {38, 3},
		32: {38, 3},
		33: {38, 3},
		34: {38, 3},
		35: {17, 3},
		36: {17, 2},
		37: {18, 3},
		38: {18, 3},
		39: {42, 1},
		40: {42, 1},
		41: {42, 2},
		42: {42, 2},
		43: {42, 3},
		44: {36, 1},
		45: {36, 3},
		46: {36, 2},
		47: {32, 1},
		48: {32, 1},
		49: {32, 6},
		50: {32, 8},
		51: {34, 1},
		52: {34, 1},
		53: {34, 2},
		54: {34, 1},
		55: {39, 1},
		56: {39, 1},
		57: {39, 1},
		58: {39, 1},
		59: {39, 1},
		60: {39, 1},
		61: {39, 1},
		62: {39, 1},
		63: {41, 1},
		64: {41, 1},
		65: {30, 1},
		66: {30, 2},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [97][]uint16{
		// 0
		{2: 74, 17: 72, 73, 71, 21: 70, 28: 69, 43: 68},
		{4: 67},
		{4: 66},
		{65, 65, 127, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 160, 161, 159},
		{61, 61, 127, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 124, 125, 123, 19: 126},
		// 5
		{53, 53, 3: 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53},
		{52, 52, 3: 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52},
		{78, 2: 74, 17: 72, 73, 71, 87, 70, 88, 24: 76, 75, 85, 82, 84, 30: 77, 81, 83, 86, 36: 80, 42: 79},
		{41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41},
		{40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40},
		// 10
		{120, 31: 121},
		{31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31},
		{119},
		{118, 106},
		{28, 20: 87, 22: 88, 30: 117},
		// 15
		{27},
		{23, 23},
		{20, 20},
		{19, 19},
		{37: 90},
		// 20
		{2, 2, 3: 2, 31: 2},
		{20: 89},
		{1, 1, 3: 1, 31: 1},
		{2: 74, 17: 72, 73, 71, 21: 70, 28: 91},
		{5: 94, 96, 97, 102, 98, 99, 95, 103, 101, 100, 39: 92, 41: 93},
		// 25
		{2: 74, 17: 72, 73, 71, 87, 70, 113, 112, 28: 111, 30: 114, 34: 110},
		{2: 104},
		{2: 12, 19: 12, 12, 12, 12, 12},
		{2: 11, 19: 11, 11, 11, 11, 11},
		{2: 10, 19: 10, 10, 10, 10, 10},
		// 30
		{2: 9, 19: 9, 9, 9, 9, 9},
		{2: 8, 19: 8, 8, 8, 8, 8},
		{2: 7, 19: 7, 7, 7, 7, 7},
		{2: 6, 19: 6, 6, 6, 6, 6},
		{2: 5, 19: 5, 5, 5, 5, 5},
		// 35
		{2: 4},
		{2: 3},
		{2: 74, 17: 72, 73, 71, 21: 70, 24: 76, 75, 85, 28: 84, 32: 83, 86, 36: 105},
		{107, 106},
		{21, 21, 74, 17: 72, 73, 71, 21: 70, 24: 76, 75, 85, 28: 84, 32: 109, 86},
		// 40
		{3: 108},
		{17, 17},
		{22, 22},
		{3: 116},
		{1: 16, 3: 16},
		// 45
		{1: 15, 3: 15},
		{20: 89, 23: 115},
		{1: 13, 3: 13},
		{1: 14, 3: 14},
		{18, 18},
		// 50
		{26},
		{29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30},
		{32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32},
		{25, 20: 87, 22: 88, 30: 122},
		// 55
		{24},
		{60, 60, 3: 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60},
		{2: 74, 17: 134, 135, 24: 76, 144, 133, 136, 29: 157, 35: 158},
		{2: 74, 17: 134, 135, 24: 76, 75, 133, 136, 29: 156},
		{57, 57, 127, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 130, 131, 129},
		// 60
		{78, 20: 87, 22: 88, 30: 128},
		{120},
		{56, 56, 3: 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56},
		{2: 74, 17: 134, 135, 24: 76, 75, 133, 136, 29: 155},
		{2: 74, 17: 134, 135, 24: 76, 75, 133, 136, 29: 132},
		// 65
		{54, 54, 74, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 139, 140, 137, 138},
		{50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50},
		{49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49},
		{48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48},
		{47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47},
		// 70
		{46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46},
		{45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45},
		{2: 74, 17: 134, 135, 24: 76, 144, 133, 136, 29: 142, 35: 143},
		{2: 74, 17: 134, 135, 24: 76, 75, 133, 136, 29: 141},
		{43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 137, 138},
		// 75
		{44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 137, 138},
		{42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42},
		{41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 37: 145},
		{2: 74, 147, 17: 72, 73, 71, 87, 70, 113, 112, 28: 111, 30: 114, 34: 148, 38: 146},
		{1: 150, 3: 149},
		// 80
		{38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38},
		{1: 37, 3: 37},
		{39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39},
		{2: 74, 17: 72, 73, 71, 87, 70, 113, 112, 152, 28: 111, 30: 114, 34: 151, 40: 154, 44: 153},
		{1: 36, 3: 36},
		// 85
		{1: 35, 3: 35},
		{1: 34, 3: 34},
		{1: 33, 3: 33},
		{55, 55, 74, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 139, 140, 137, 138},
		{58, 58, 74, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 139, 140, 137, 138},
		// 90
		{59, 59, 74, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 139, 140, 137, 138},
		{51, 51, 3: 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51},
		{64, 64, 3: 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64},
		{2: 74, 17: 134, 135, 24: 76, 75, 133, 136, 29: 163},
		{2: 74, 17: 134, 135, 24: 76, 75, 133, 136, 29: 162},
		// 95
		{62, 62, 74, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 139, 140, 137, 138},
		{63, 63, 74, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 139, 140, 137, 138},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 51

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*parser).expr = yyS[yypt-0].Expr
		}
	case 2:
		{
			yyVAL.Expr = RootSymbol
		}
	case 3:
		{
			yyVAL.Expr = &BinaryExpr{Left: RootSymbol, Right: yyS[yypt-0].Expr, Op: NEXT_SELECT}
		}
	case 4:
		{
			yyVAL.Expr = &BinaryExpr{Left: RootSymbol, Right: yyS[yypt-0].Expr, Op: DOT}
		}
	case 5:
		{
			yyVAL.Expr = &BinaryExpr{Left: RootSymbol, Right: yyS[yypt-0].Expr, Op: DOTDOT}
		}
	case 6:
		{
			yyVAL.Expr = CurrentSymbol
		}
	case 7:
		{
			yyVAL.Expr = &BinaryExpr{Left: CurrentSymbol, Right: yyS[yypt-0].Expr, Op: NEXT_SELECT}
		}
	case 8:
		{
			yyVAL.Expr = &BinaryExpr{Left: CurrentSymbol, Right: yyS[yypt-0].Expr, Op: DOT}
		}
	case 9:
		{
			yyVAL.Expr = &BinaryExpr{Left: CurrentSymbol, Right: yyS[yypt-0].Expr, Op: DOTDOT}
		}
	case 10:
		{
			yyVAL.Expr = ParentSymbol
		}
	case 11:
		{
			yyVAL.Expr = &BinaryExpr{Left: ParentSymbol, Right: yyS[yypt-0].Expr, Op: NEXT_SELECT}
		}
	case 12:
		{
			yyVAL.Expr = &BinaryExpr{Left: ParentSymbol, Right: yyS[yypt-0].Expr, Op: DOT}
		}
	case 13:
		{
			yyVAL.Expr = &BinaryExpr{Left: ParentSymbol, Right: yyS[yypt-0].Expr, Op: DOTDOT}
		}
	case 14:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 15:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 16:
		{
			yyVAL.Expr = &BinaryExpr{Left: CurrentSymbol, Right: yyS[yypt-0].CallExpr, Op: NEXT_CALL}
		}
	case 17:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 18:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 19:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 20:
		{
			yyVAL.Expr = WildcardSymbol
		}
	case 21:
		{
			yyVAL.Expr = &BinaryExpr{Left: yyS[yypt-1].Expr, Right: yyS[yypt-0].Expr, Op: NEXT_SELECT}
		}
	case 22:
		{
			yyVAL.Expr = &BinaryExpr{Left: yyS[yypt-1].Expr, Right: yyS[yypt-0].Expr, Op: NEXT_SELECT}
		}
	case 23:
		{
			yyVAL.Expr = &BinaryExpr{Left: yyS[yypt-2].Expr, Right: yyS[yypt-0].Expr, Op: DOT}
		}
	case 24:
		{
			yyVAL.Expr = &BinaryExpr{Left: yyS[yypt-2].Expr, Right: yyS[yypt-0].Expr, Op: DOTDOT}
		}
	case 25:
		{
			yyVAL.Expr = &BinaryExpr{Left: yyS[yypt-2].Expr, Right: yyS[yypt-0].CallExpr, Op: NEXT_CALL}
		}
	case 26:
		{
			yyVAL.Expr = MemberExpr(yyS[yypt-0].str)
		}
	case 27:
		{
			yyVAL.Expr = StringExpr(yyS[yypt-0].str)
		}
	case 28:
		{
			yyVAL.CallExpr = yylex.(*parser).NewCallExpr(yyS[yypt-3].str, yyS[yypt-1].Exprs)
		}
	case 29:
		{
			yyVAL.CallExpr = yylex.(*parser).NewCallExpr(yyS[yypt-2].str, nil)
		}
	case 30:
		{
			yyVAL.Exprs = []Expr{yyS[yypt-0].Expr}
		}
	case 31:
		{
			yyVAL.Exprs = append(yyS[yypt-2].Exprs, yyS[yypt-0].Expr)
		}
	case 32:
		{
			yyVAL.Exprs = append(yyS[yypt-2].Exprs, yyS[yypt-0].str)
		}
	case 33:
		{
			yyVAL.Exprs = append(yyS[yypt-2].Exprs, yyS[yypt-0].boolVal)
		}
	case 34:
		{
			yyVAL.Exprs = append(yyS[yypt-2].Exprs, yyS[yypt-0].boolVal)
		}
	case 35:
		{
			yyVAL.Expr = IndexExpr(yyS[yypt-1].intVal)
		}
	case 36:
		{
			yyVAL.Expr = &EmptyGroup{Owner: nil}
		}
	case 37:
		{
			yyVAL.Expr = yyS[yypt-1].Expr
		}
	case 38:
		{
			yyVAL.Expr = yyS[yypt-1].MatcherExpr
		}
	case 39:
		{
			yyVAL.Expr = RangeExpr{0, -1}
		}
	case 40:
		{
			yyVAL.Expr = RangeExpr{0, -1}
		}
	case 41:
		{
			yyVAL.Expr = RangeExpr{0, yyS[yypt-0].intVal}
		}
	case 42:
		{
			yyVAL.Expr = RangeExpr{yyS[yypt-1].intVal, -1}
		}
	case 43:
		{
			yyVAL.Expr = RangeExpr{yyS[yypt-2].intVal, yyS[yypt-0].intVal}
		}
	case 44:
		{
			yyVAL.MatcherExpr = MatcherExpr{yyS[yypt-0].Expr}
		}
	case 45:
		{
			yyVAL.MatcherExpr = append(yyS[yypt-2].MatcherExpr, yyS[yypt-0].Expr)
		}
	case 46:
		{
			yyVAL.MatcherExpr = yyS[yypt-1].MatcherExpr
		}
	case 47:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 48:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 49:
		{
			yyVAL.Expr = &FilterExpr{Body: &BinaryExpr{Left: yyS[yypt-3].Expr, Right: yyS[yypt-1].Expr, Op: yyS[yypt-2].op}}
		}
	case 50:
		{
			yyVAL.Expr = &FilterExpr{Body: &BinaryExpr{Left: yyS[yypt-5].Expr, Right: yyS[yypt-2].MatcherExpr, Op: yyS[yypt-4].op}}
		}
	case 51:
		{
			yyVAL.Expr = yyS[yypt-0].Expr
		}
	case 52:
		{
			yyVAL.Expr = yyS[yypt-0].falVal
		}
	case 53:
		{
			yyVAL.Expr = float64(-yyS[yypt-0].falVal)
		}
	case 54:
		{
			yyVAL.Expr = yyS[yypt-0].intVal
		}
	case 55:
		{
			yyVAL.op = EQ
		}
	case 56:
		{
			yyVAL.op = NEQ
		}
	case 57:
		{
			yyVAL.op = GT
		}
	case 58:
		{
			yyVAL.op = GTE
		}
	case 59:
		{
			yyVAL.op = LT
		}
	case 60:
		{
			yyVAL.op = LTE
		}
	case 61:
		{
			yyVAL.op = RE
		}
	case 62:
		{
			yyVAL.op = NRE
		}
	case 63:
		{
			yyVAL.op = IN
		}
	case 64:
		{
			yyVAL.op = NIN
		}
	case 65:
		{
			yyVAL.intVal = yyS[yypt-0].intVal
		}
	case 66:
		{
			yyVAL.intVal = -yyS[yypt-0].intVal
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
